import moment from 'moment';

const DURATION_TO_PERIOD_START_AMOUNT = 1;
const DURATION_TO_PERIOD_START_UNIT = 'hour';
export const DURATION_TO_PERIOD_START = moment.duration(
  DURATION_TO_PERIOD_START_AMOUNT,
  DURATION_TO_PERIOD_START_UNIT,
);

const DURATION_TO_PERIOD_END_AMOUNT = 1;
const DURATION_TO_PERIOD_END_UNIT = 'hour';
export const DURATION_TO_PERIOD_END = moment.duration(
  DURATION_TO_PERIOD_END_AMOUNT,
  DURATION_TO_PERIOD_END_UNIT,
);

const DURATION_INTERVAL_AMOUNT = 5;
const DURATION_INTERVAL_UNIT = 'minutes';
export const DURATION_INTERVAL = moment.duration(
  DURATION_INTERVAL_AMOUNT,
  DURATION_INTERVAL_UNIT,
);

export const INTERVAL = '5T';
